## Linear regression model from scratch

In [42]:
import numpy as np
import torch

In [43]:
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

In [44]:
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [45]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [46]:
weight = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

In [47]:
inputs @ weight.t() + bias

tensor([[ -67.3654,  107.2294],
        [ -78.8072,  134.0055],
        [ -28.6790,  172.0776],
        [-144.1005,  114.3143],
        [ -30.0668,  119.3574]], grad_fn=<AddBackward0>)

In [48]:
def model(inputs):
    return inputs @ weight.t() + bias

In [49]:
prediction = model(inputs)
print(prediction)

tensor([[ -67.3654,  107.2294],
        [ -78.8072,  134.0055],
        [ -28.6790,  172.0776],
        [-144.1005,  114.3143],
        [ -30.0668,  119.3574]], grad_fn=<AddBackward0>)


## Loss function

In [50]:
diff0 = prediction - targets
torch.sum(diff0 * diff0) / diff0.numel()

tensor(12490.3350, grad_fn=<DivBackward0>)

In [51]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [52]:
loss = mse(prediction, targets)
print(loss)

tensor(12490.3350, grad_fn=<DivBackward0>)


## Compute gradient

In [53]:
loss.backward()
print(weight.grad)
print(bias.grad)

tensor([[-12504.0117, -12406.8467,  -7911.6299],
        [  4745.1426,   4149.8154,   2646.8726]])
tensor([-146.0038,   53.1968])


## Train the model using gradient descent

In [54]:
with torch.no_grad():
    weight -= weight.grad * 1e-5
    bias -= bias.grad * 1e-5
    weight.grad.zero_()
    bias.grad.zero_()

In [55]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(8668.8906, grad_fn=<DivBackward0>)


In [56]:
for i in range(100):
    prediction = model(inputs)
    loss = mse(prediction, targets)
    loss.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()

In [57]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(262.5763, grad_fn=<DivBackward0>)


In [58]:
prediction

tensor([[ 52.8134,  62.3363],
        [ 77.0638,  77.9776],
        [137.3870, 119.9977],
        [ -4.6456,  50.5734],
        [108.0294,  77.3089]], grad_fn=<AddBackward0>)

In [59]:
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])